language: minimal
stages:
  - install
  - build
jobs:
  include:
    - stage: install
      name: "Latex installation"
      script:
          - apt-get -qq update && apt-get install -y --no-install-recommends latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base
          - apt-get -qq update && apt-get install -y --no-install-recommends texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-xetex
          - apt-get -qq update && apt-get install -y --no-install-recommends texlive-pictures texlive-lang-french lmodern fonts-font-awesome
    - stage: build
      name: "Build PDF"
      script:
          - latexmk -cd -f -lualatex -interaction=nonstopmode -synctex=1 cv.tex
